export type Label =
   | 'niño'
   | 'niña'
   | 'hombre'
   | 'moda'
   | 'mujer'
   | 'ver todo'
   | 'iluminación'
   | 'salón y comedor'
   | 'cocina'
   | 'salon'
   | 'comedor'
   | 'dormitorio'
   | 'telefonía'
   | 'informática'
   | 'salud y masages'
   | 'perfumes y belleza'
   | 'entretenimiento y deporte'
   | 'entretenimiento'
   | 'deporte'
   | 'perfumes'
   | 'belleza'
   | 'salud'
   | 'masages'
   | 'paddel'
   | 'tennis'
   | 'running'
   | 'ciclismo'
