export type Label =
   | 'niño'
   | 'niña'
   | 'hombre'
   | 'mujer'
   | 'ver todo'
   | 'iluminacion'
   | 'cocina'
   | 'salon'
   | 'comedor'
   | 'dormitorio'
   | 'telefonia'
   | 'entretenimiento'
   | 'deporte'
   | 'perfumes'
   | 'belleza'
   | 'salud'
   | 'masages'
   | 'paddel'
   | 'tennis'
   | 'running'
   | 'ciclismo'
